version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "greet-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1m0sf4zgwlxb9"
s3_prefix = "greet-app"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
