AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  greet-app

  Sample SAM Template for greet-app
  
Parameters:
  ServiceName:
    Type: String
    Default: greetings-api
  Stage:
    Description: The deployment stage dev or prod
    Type: String
    Default: dev


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub "${ServiceName}-${Stage}-get-hello"
      Description: 'Returns the greeting hello'
      CodeUri: src/functions/hello
      Handler: handler.default
      Runtime: nodejs12.x
      Tags:
        'greenhorn:project': 'MyProject'
        'greenhorn:service-name': !Sub "${ServiceName}"
        'greenhorn:owner': 'Fred Flinstone'
      Events:
        Hello:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
  GoodbyeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub "${ServiceName}-${Stage}-get-goodbye"
      Description: 'Returns the greeting goodbye'
      CodeUri: src/functions/goodbye
      Handler: handler.default
      Runtime: nodejs12.x
      Tags:
        'greenhorn:project': 'MyProject'
        'greenhorn:service-name': !Sub "${ServiceName}"
        'greenhorn:owner': 'Fred Flinstone'
      Events:
        Goodbye:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /goodbye
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  GoodbyeApi:
    Description: "API Gateway endpoint URL for Prod stage for Goodbye function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/goodbye/"

  